[book]
title = "XSCP Specification"
description = "Official specification for XSCP (XSCP Stream Communication Protocol)"
authors = ["Iván Amón"]
language = "en"

[output.html]
git-repository-url = "https://github.com/ivan-amon/xscp-spec"
default-theme = "ayu"
preferred-dark-theme = "ayu"
copy-fonts = true